### ISSUE TITLE
Possible copy and paste bug in PIAACMCsimul.c

### ISSUE THREAD

**Issue by stevepur** [oguyon/PIAACMCdesign#8]
From Chris: I got a little more time this morning to look at the PIAACMCdesign code,
followed up on something that is seg faulting in step007 with agressive
optimization, and ran into some confusing code. I'm hoping you can
answer a few questions about it.

In   PIAACMCsimul.c::PIAACMCsimul_exec() the following variables
are declared on the stack, and not initialized:

```
long i, ii, jj, kk;
```

The first part of the function is a giant branch, switching on 'mode'.
For some of the modes, variable ii is used in one or more loops, and
ends up with the loop termination value, e.g.

for(ii=0;ii<xsize_ysize_zsize; ii++) ...

For step007, mode=40 and ii is not set, so it gets a random stack
value. Then LINOPT==1, so we drop into that code next, where we
use jj as a loop variable, but assign into F[ii]

 for(jj=0; jj<data.image[piaacmc[0].piaa0CmodesID].md[0].size[0]; jj++)
                {
                    tmp = piaa0C_regcoeff \* (data.image[ID].array.F[jj]-data.image[IDref].array.F[jj]) \* pow(1.0_jj,piaa0C_regcoeff_alpha);
                    data.image[ID1Dref].array.F[ii] = tmp;
                    val0 += tmp_tmp;
                }

Depending on ii, it will either seg fault here, or continue to uselessly
overwrite the same F[ii] location. There are 3 more jj loops with the
same assignment to F[ii], and many compiler optimization routines
will remove them, since if not fatal the assignment is idempotent.

There are lots more locations where this same pattern is repeated. Is
the [ii] just a typo? I thought this might be the case, but the next thing
the code does in step007 is to use ii as a loop variable

for(ii=0; ii<data.image[ID].md[0].nelement; ii++)

so it is left with value nelement (4872) at loop termination. Then there
are a bunch of loops that look like this

```
for(jj=0; jj<data.image[piaacmc[0].piaa0CmodesID].md[0].size[0]; jj++)
        {
            data.image[ID1Dref].array.F[ii] = piaa0C_regcoeff * (data.image[ID].array.F[jj]-data.image[IDref].array.F[jj]) * pow(1.0*jj, piaa0C_regcoeff_alpha);
            data.image[IDm].array.F[ii] = 1.0;
            ii++;
        }
```

Now we have a loop indexed by jj and assign into F[ii], but also increment ii,
so perhaps this is deliberate? If not deliberate, there are some crazy
assignments going on. If deliberate, this is incredibly confusing code.

**Comment by oguyon** [comment]
fixed in version 1.2.18
I also documented in the source code so that it's now clear what this is all about
These sections of the code compute the regularization metric, and there were indeed multiple serious errors, due to my use of "copy & paste" without doing the required modifications.
In the new code, you'll see that when index ii is used, it is now initiated and incremented (ii++) at each iteration of the jj  loop. As the jj loop computes "sub-vectors", these "sub-vectors" are added to a main vector (index ii).
This code section is found multiple times in the .c file. There are two variants:
- the overall performance metric is computed but the ii-indexed vector is not written
- the ii-indexed vector is written
